FROM wlt184074150/python

RUN pip install Flask
RUN pip install python-memcached
RUN pip install requests
RUN pip install Appium-Python-Client
RUN pip install Flask-APScheduler
RUN pip install celery
RUN pip install APScheduler

RUN pip install Flask-MySQL
RUN pip install MySQL-python

RUN pip install selenium
RUN pip install tornado
RUN pip install redis
RUN pip install psycopg2
RUN pip install Flask-SQLAlchemy
RUN pip install SQLAlchemy
RUN pip install Django
RUN pip install peewee
